name = "uzura2_fpm"
version = "0.2.0"
license = "MIT"
author = "C H"
maintainer = "curehoney2014@gmail.com"
copyright = "Copyright 2021, C.H."
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
